# Generated by Django 3.2.13 on 2022-10-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='attachment/image/', verbose_name='게시글 이미지')),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진 목록',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '게시글 좋아요',
                'verbose_name_plural': '게시글 좋아요 목록',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='게시글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='게시글 생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='게시글 갱신일')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 목록',
            },
        ),
    ]
