# Generated by Django 3.2.13 on 2022-10-22 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일 주소')),
                ('fullname', models.CharField(max_length=20, verbose_name='이름')),
                ('password', models.CharField(max_length=300, verbose_name='비밀번호')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='휴대폰')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='프로필 갱신일')),
                ('like_post', models.ManyToManyField(related_name='user_like_post', through='posts.Like', to='posts.Post', verbose_name='좋아요 누른 글')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile/image/', verbose_name='프로필 사진')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='프로필 이름')),
                ('info', models.TextField(verbose_name='프로필 소개')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL, verbose_name='사용자 프로필')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
            },
        ),
    ]
