# Generated by Django 3.2.13 on 2022-10-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='댓글 생성일')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='댓글 갱신일')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
            },
        ),
    ]
