# Generated by Django 3.2.13 on 2022-10-22 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_comment', to='comments.comment', verbose_name='좋아요 누른 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_comment_user', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사람')),
            ],
            options={
                'verbose_name': '댓글 좋아요',
                'verbose_name_plural': '댓글 좋아요 목록',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_like_user',
            field=models.ManyToManyField(related_name='comment_like_user', through='comments.CommentLike', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사람'),
        ),
    ]
